import * as React from "react";
import { View, Text } from 'react-native';

export const Message = React.memo(() => {
    return <View>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
        <Text>asds</Text>
    </View>
})